const API_URL = "http://43.205.104.30:9000/"; //main server

// const API_URL = "http://localhost:9000/"; //test server

const BASE_URL = API_URL + "api/";

const constants = {
  URL: {
    BASE_URL: API_URL + "api",
    SIGNIN: BASE_URL + "auth/signIn",
    FORGOT_PASSWORD: BASE_URL + "emailVerification",
    VERIFY_TOKEN: BASE_URL + "verifyPasswordResetToken",
    RESET_PASSWORD: BASE_URL + "resetPassword",
    REFRESH_TOKEN: BASE_URL + "auth/getNewAccessToken",
    EMPLOYEES_LIST: BASE_URL + "user",
    GAME_LEVELS: BASE_URL + "level",
    levelDashboardAllUsers: BASE_URL + "levelDashboardAllUsers",
    getUserLvlDashboard: BASE_URL + "getUserLvlDashboard",
    // LEVEL_DASHBOARD: BASE_URL + "getLevelReport",
    // LEVEL_PROCESS_DETAILS: BASE_URL + "getLevelReportUser",
    // LEVEL_ONE_ALL_SCORE_BY_USERID: BASE_URL + "getAllScoreByLevelUserId",
    LEVEL_ONE_SCORE_BY_USERID: BASE_URL + "getScoreByLevelUserId",
    LEVEL_ONE_SCORE_BY_GAME_USERID: BASE_URL + "getScoreByGameUserId",
    GAME_CATEGORIES: BASE_URL + "category",
    GAME_NAMES: BASE_URL + "game",
    DuplicateGAMES: BASE_URL + "duplicateGameWithQuestions",
    GAME_QUESTIONS: BASE_URL + "imageTextQA",
    GAME_QUESTIONS_LIST: BASE_URL + "getQAsByGameId",
    UPLOAD: BASE_URL + "file/upload-singlePDF",
    SCORE: BASE_URL + "gameScore",
    RATING_QA: BASE_URL + "getGameByRatingQA",
    PROCESS: BASE_URL + "process",
    PROCESS_MATRIX: BASE_URL + "getProcessMatrixByLevelId",
    LEVEL_ONE_GAMES: BASE_URL + "getGameByLevelId",
    ALL_PROCESS_MATRIX: BASE_URL + "processMatrix",
    PROCESS_LIST: BASE_URL + "getProcessForMatrix",
    DEPARTMENT: BASE_URL + "department",
     CONTRACTOR: BASE_URL + "contractor",
    EMPLOYEE_DEPARTMENT: BASE_URL + "empDeploy",
    USER_DEPLOYMENT_DETAIL_LIST: BASE_URL + "empDeployUserId",
    APPRECIATION: BASE_URL + "appreciation",
    APPRECIATION_USERID: BASE_URL + "getAppreciationByUserId",
    REPORTCARD: BASE_URL + "getSkillMatrixByUserId",
    SKILLMATRIX: BASE_URL + "skillMatrix",
    FEEDBACK_FORM: BASE_URL + "setupQA",
    FEEDBACK_QUESTION: BASE_URL + "getSetByOnJobProcess",
    PEOPLE_COUNT: BASE_URL + "getUserJoiningCards",
    PROCESS_LEVEL_ANALYSIS: BASE_URL + "getProcessLevelAnalysis",
    MONTH_LEVEL_ANALYSIS: BASE_URL + "getMonthLevelAnalysis/",
    GET_CATEGORY_ON_JOB: BASE_URL + "getCategoryOnJob",
    USER_FOR_ON_JOB: BASE_URL + "getEligibleUserForOnJob/",
    GAME_CHANCE_DETAIL: BASE_URL + "checkGameChangeByUsrGmeId",
    EVENT: BASE_URL + "eventSchedules",
  },
};
export default constants;
